namespace Vertex.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CleanUp : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Post", "CategoryId", "dbo.Category");
            DropIndex("dbo.Post", new[] { "CategoryId" });
            AddColumn("dbo.ApplyJob", "ApplyDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Post", "Description", c => c.String());
            AddColumn("dbo.Post", "CreateDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Post", "UpdateDateUtc", c => c.DateTime());
            AddColumn("dbo.Post", "Format", c => c.String(maxLength: 32));
            AddColumn("dbo.Post", "FormatValue", c => c.String());
            AddColumn("dbo.Comment", "Email", c => c.String(maxLength: 128));
            AddColumn("dbo.Comment", "Commentary", c => c.String(maxLength: 500));
            AddColumn("dbo.Comment", "CommentDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Contact", "FullName", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.Contact", "Phone", c => c.String(maxLength: 16));
            AddColumn("dbo.Contact", "DateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Job", "JobType", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.Job", "CreateDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Job", "UpdateDateUtc", c => c.DateTime());
            AddColumn("dbo.MediaStorage", "CreateDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.MediaStorage", "UpdateDateUtc", c => c.DateTime());
            AddColumn("dbo.Portfolio", "CreateDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Portfolio", "UpdateDateUtc", c => c.DateTime());
            AddColumn("dbo.Portfolio", "Format", c => c.String(maxLength: 32));
            AddColumn("dbo.Portfolio", "FormatValue", c => c.String());
            AddColumn("dbo.Subscriber", "SubscribeDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Subscriber", "UnSubscribeDateUtc", c => c.DateTime());
            AddColumn("dbo.TeamMember", "FullName", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.TeamMember", "CreateDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.TeamMember", "UpdateDateUtc", c => c.DateTime());
            AddColumn("dbo.Testimonials", "CreateDateUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Testimonials", "UpdateDateUtc", c => c.DateTime());
            AddColumn("dbo.AspNetUsers", "PictureId", c => c.Int());
            AddColumn("dbo.AspNetUsers", "Name", c => c.String());
            AddColumn("dbo.AspNetUsers", "Surname", c => c.String());
            AddColumn("dbo.AspNetUsers", "Location", c => c.String());
            AlterColumn("dbo.Category", "Name", c => c.String(maxLength: 128));
            AlterColumn("dbo.Post", "Title", c => c.String(nullable: false, maxLength: 512));
            AlterColumn("dbo.Post", "ViewName", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Post", "UserId", c => c.String(nullable: false));
            AlterColumn("dbo.Comment", "FullName", c => c.String(maxLength: 128));
            AlterColumn("dbo.Contact", "Email", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Contact", "Subject", c => c.String(nullable: false, maxLength: 256));
            AlterColumn("dbo.Contact", "Message", c => c.String(nullable: false, maxLength: 512));
            AlterColumn("dbo.Job", "Title", c => c.String(nullable: false, maxLength: 512));
            AlterColumn("dbo.Job", "Description", c => c.String(nullable: false));
            AlterColumn("dbo.Job", "Location", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.JobCategory", "Name", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.MediaStorage", "EntityId", c => c.String(maxLength: 128));
            AlterColumn("dbo.MediaStorage", "EntityName", c => c.String(maxLength: 128));
            AlterColumn("dbo.MediaStorage", "FileName", c => c.String(maxLength: 256));
            AlterColumn("dbo.MediaStorage", "FilePath", c => c.String(maxLength: 512));
            AlterColumn("dbo.MediaStorage", "MimeType", c => c.String(maxLength: 32));
            AlterColumn("dbo.Portfolio", "Title", c => c.String(nullable: false, maxLength: 512));
            AlterColumn("dbo.Portfolio", "Description", c => c.String(nullable: false));
            AlterColumn("dbo.Portfolio", "ViewName", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Portfolio", "UserId", c => c.String(nullable: false));
            AlterColumn("dbo.PortfolioCategory", "Name", c => c.String(maxLength: 128));
            AlterColumn("dbo.PostTag", "Name", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Setting", "Name", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Setting", "Description", c => c.String(maxLength: 512));
            AlterColumn("dbo.Setting", "Value", c => c.String(nullable: false));
            AlterColumn("dbo.Setting", "DataType", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.SocialNetwork", "EntityName", c => c.String(maxLength: 128));
            AlterColumn("dbo.SocialNetwork", "WebAddress", c => c.String(nullable: false, maxLength: 512));
            AlterColumn("dbo.Subscriber", "Email", c => c.String(nullable: false));
            AlterColumn("dbo.TeamMember", "Position", c => c.String(maxLength: 128));
            AlterColumn("dbo.Testimonials", "CompanyName", c => c.String(maxLength: 256));
            AlterColumn("dbo.Testimonials", "WebSiteUrl", c => c.String(maxLength: 512));
            AlterColumn("dbo.Testimonials", "EmployeName", c => c.String(maxLength: 128));
            AlterColumn("dbo.UrlRecord", "EntityName", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UrlRecord", "Slug", c => c.String(nullable: false));
            DropColumn("dbo.ApplyJob", "ApplyDate");
            DropColumn("dbo.Post", "ShortContent");
            DropColumn("dbo.Post", "Content");
            DropColumn("dbo.Post", "CreateDate");
            DropColumn("dbo.Post", "UpdateDate");
            DropColumn("dbo.Post", "PostFormat");
            DropColumn("dbo.Post", "PostFormatValue");
            DropColumn("dbo.Comment", "EmailAddress");
            DropColumn("dbo.Comment", "Content");
            DropColumn("dbo.Comment", "CommentDate");
            DropColumn("dbo.Contact", "Name");
            DropColumn("dbo.Contact", "Date");
            DropColumn("dbo.Job", "WorkType");
            DropColumn("dbo.Job", "CreateDate");
            DropColumn("dbo.Job", "UpdateDate");
            DropColumn("dbo.MediaStorage", "CreatedOnUtc");
            DropColumn("dbo.MediaStorage", "UpdatedOnUtc");
            DropColumn("dbo.Portfolio", "Content");
            DropColumn("dbo.Portfolio", "CreateDate");
            DropColumn("dbo.Portfolio", "UpdateDate");
            DropColumn("dbo.Portfolio", "PortfolioFormat");
            DropColumn("dbo.Portfolio", "PortfolioFormatValue");
            DropColumn("dbo.Subscriber", "SubscribeDate");
            DropColumn("dbo.Subscriber", "UnsubscribeDate");
            DropColumn("dbo.TeamMember", "Name");
            DropColumn("dbo.TeamMember", "CreateDate");
            DropColumn("dbo.TeamMember", "UpdateDate");
            DropColumn("dbo.Testimonials", "CreateDate");
            DropColumn("dbo.Testimonials", "UpdateDate");
            DropColumn("dbo.AspNetUsers", "AvatarId");
        }
        
        public override void Down()
        {
            AddColumn("dbo.AspNetUsers", "AvatarId", c => c.Int());
            AddColumn("dbo.Testimonials", "UpdateDate", c => c.DateTime());
            AddColumn("dbo.Testimonials", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.TeamMember", "UpdateDate", c => c.DateTime());
            AddColumn("dbo.TeamMember", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.TeamMember", "Name", c => c.String());
            AddColumn("dbo.Subscriber", "UnsubscribeDate", c => c.DateTime());
            AddColumn("dbo.Subscriber", "SubscribeDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Portfolio", "PortfolioFormatValue", c => c.String());
            AddColumn("dbo.Portfolio", "PortfolioFormat", c => c.String(maxLength: 50));
            AddColumn("dbo.Portfolio", "UpdateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Portfolio", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Portfolio", "Content", c => c.String());
            AddColumn("dbo.MediaStorage", "UpdatedOnUtc", c => c.DateTime());
            AddColumn("dbo.MediaStorage", "CreatedOnUtc", c => c.DateTime(nullable: false));
            AddColumn("dbo.Job", "UpdateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Job", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Job", "WorkType", c => c.String(maxLength: 128));
            AddColumn("dbo.Contact", "Date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Contact", "Name", c => c.String(nullable: false));
            AddColumn("dbo.Comment", "CommentDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Comment", "Content", c => c.String(maxLength: 250));
            AddColumn("dbo.Comment", "EmailAddress", c => c.String(maxLength: 50));
            AddColumn("dbo.Post", "PostFormatValue", c => c.String());
            AddColumn("dbo.Post", "PostFormat", c => c.String(maxLength: 50));
            AddColumn("dbo.Post", "UpdateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Post", "CreateDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Post", "Content", c => c.String());
            AddColumn("dbo.Post", "ShortContent", c => c.String());
            AddColumn("dbo.ApplyJob", "ApplyDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.UrlRecord", "Slug", c => c.String());
            AlterColumn("dbo.UrlRecord", "EntityName", c => c.String());
            AlterColumn("dbo.Testimonials", "EmployeName", c => c.String());
            AlterColumn("dbo.Testimonials", "WebSiteUrl", c => c.String());
            AlterColumn("dbo.Testimonials", "CompanyName", c => c.String());
            AlterColumn("dbo.TeamMember", "Position", c => c.String());
            AlterColumn("dbo.Subscriber", "Email", c => c.String());
            AlterColumn("dbo.SocialNetwork", "WebAddress", c => c.String());
            AlterColumn("dbo.SocialNetwork", "EntityName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Setting", "DataType", c => c.String(maxLength: 50));
            AlterColumn("dbo.Setting", "Value", c => c.String());
            AlterColumn("dbo.Setting", "Description", c => c.String(maxLength: 500));
            AlterColumn("dbo.Setting", "Name", c => c.String(maxLength: 200));
            AlterColumn("dbo.PostTag", "Name", c => c.String());
            AlterColumn("dbo.PortfolioCategory", "Name", c => c.String(maxLength: 200));
            AlterColumn("dbo.Portfolio", "UserId", c => c.String());
            AlterColumn("dbo.Portfolio", "ViewName", c => c.String(maxLength: 150));
            AlterColumn("dbo.Portfolio", "Description", c => c.String());
            AlterColumn("dbo.Portfolio", "Title", c => c.String(maxLength: 500));
            AlterColumn("dbo.MediaStorage", "MimeType", c => c.String());
            AlterColumn("dbo.MediaStorage", "FilePath", c => c.String());
            AlterColumn("dbo.MediaStorage", "FileName", c => c.String());
            AlterColumn("dbo.MediaStorage", "EntityName", c => c.String());
            AlterColumn("dbo.MediaStorage", "EntityId", c => c.String());
            AlterColumn("dbo.JobCategory", "Name", c => c.String(maxLength: 200));
            AlterColumn("dbo.Job", "Location", c => c.String(maxLength: 500));
            AlterColumn("dbo.Job", "Description", c => c.String());
            AlterColumn("dbo.Job", "Title", c => c.String(maxLength: 500));
            AlterColumn("dbo.Contact", "Message", c => c.String(nullable: false));
            AlterColumn("dbo.Contact", "Subject", c => c.String(nullable: false));
            AlterColumn("dbo.Contact", "Email", c => c.String(nullable: false));
            AlterColumn("dbo.Comment", "FullName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Post", "UserId", c => c.String());
            AlterColumn("dbo.Post", "ViewName", c => c.String(maxLength: 50));
            AlterColumn("dbo.Post", "Title", c => c.String(maxLength: 400));
            AlterColumn("dbo.Category", "Name", c => c.String(maxLength: 200));
            DropColumn("dbo.AspNetUsers", "Location");
            DropColumn("dbo.AspNetUsers", "Surname");
            DropColumn("dbo.AspNetUsers", "Name");
            DropColumn("dbo.AspNetUsers", "PictureId");
            DropColumn("dbo.Testimonials", "UpdateDateUtc");
            DropColumn("dbo.Testimonials", "CreateDateUtc");
            DropColumn("dbo.TeamMember", "UpdateDateUtc");
            DropColumn("dbo.TeamMember", "CreateDateUtc");
            DropColumn("dbo.TeamMember", "FullName");
            DropColumn("dbo.Subscriber", "UnSubscribeDateUtc");
            DropColumn("dbo.Subscriber", "SubscribeDateUtc");
            DropColumn("dbo.Portfolio", "FormatValue");
            DropColumn("dbo.Portfolio", "Format");
            DropColumn("dbo.Portfolio", "UpdateDateUtc");
            DropColumn("dbo.Portfolio", "CreateDateUtc");
            DropColumn("dbo.MediaStorage", "UpdateDateUtc");
            DropColumn("dbo.MediaStorage", "CreateDateUtc");
            DropColumn("dbo.Job", "UpdateDateUtc");
            DropColumn("dbo.Job", "CreateDateUtc");
            DropColumn("dbo.Job", "JobType");
            DropColumn("dbo.Contact", "DateUtc");
            DropColumn("dbo.Contact", "Phone");
            DropColumn("dbo.Contact", "FullName");
            DropColumn("dbo.Comment", "CommentDateUtc");
            DropColumn("dbo.Comment", "Commentary");
            DropColumn("dbo.Comment", "Email");
            DropColumn("dbo.Post", "FormatValue");
            DropColumn("dbo.Post", "Format");
            DropColumn("dbo.Post", "UpdateDateUtc");
            DropColumn("dbo.Post", "CreateDateUtc");
            DropColumn("dbo.Post", "Description");
            DropColumn("dbo.ApplyJob", "ApplyDateUtc");
            CreateIndex("dbo.Post", "CategoryId");
            AddForeignKey("dbo.Post", "CategoryId", "dbo.Category", "Id");
        }
    }
}
