// <auto-generated />
namespace Vertex.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsRead : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsRead));
        
        string IMigrationMetadata.Id
        {
            get { return "201907222120064_IsRead"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
